VKCOM/vkui-tokens

- .github/workflows/coverage.yml
- .github/workflows/publish_dev.yml
- .github/workflows/publish_from_git.yml
- .github/workflows/publish_release.yml
- .github/workflows/test.yml
- package.json
> Node 14 -> 17 в Actions, поправил сборку

- src/interfaces/general/geometry/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
Токены для компонента SubnavigationBar
- Для регулирования расстояния между элементами  `size_subnavigation_bar_gap`
- Внешние отступы верхний и нижний регулируются токеном `size_subnavigation_bar_padding_vertical`
> feat: add sizeSubnavigationBarGap & sizeSubnavigationBarPaddingVertical

- package.json
- src/themeDescriptions/themes/vkCom/appearance.test.ts
- src/themeDescriptions/themes/vkCom/appearance.ts
- src/themeDescriptions/themes/vkCom/index.ts
- tsconfig.json
- yarn.lock
> feat(vkCom): import Appearance

- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
В темной теме цвета hover и active от `#ffffff` будут тем же `#ffffff`
> fix: hover&active `#ffffff` in dark theme

- package.json
- yarn.lock
Необходимо для возможности обновлять на проекте,
без обновления vkui-tokens
> chore: `csstype` use caret ranges

- src/themeDescriptions/themes/vkCom/index.ts
Исправляем цвета `colorStrokeAccentThemed` и  `colorBackgroundAccentThemed` для темной темы vkCom
> fix(vkCom): background & stroke AccentThemed

- src/themeDescriptions/themes/vkCom/index.ts
Добавлен размер Subhead типографики 14px, для команды VKCOM Kit, чтобы использовать одинаковые размеры Regular и Compact в компонентах Kit'а
> Change size Subhead Compact size 13 → 14 for vkCom

- .github/dependabot.yml
Удаляем из dependabot.yml @VKCOM/vkui-core
> ci: remove vkui-core from dependabot.yml

- src/interfaces/themes/calendar/index.ts
- src/themeDescriptions/themes/calendar/index.ts
**Изменены токены на светлой теме:**
- `calendarColorBackgroundPositiveTintAlpha4` - используется, значение на светлой теме похожи, изменения не …
> CLND-9275: Add event color tokens from calendar palette

- .github/dependabot.yml
---
Увеличила лимит PR'ов до 10, потому что [часто](https://github.com/VKCOM/vkui-tokens/network/updates/13759000/jobs) упирались в лимит
Добавила …
> chore: up dependabot limit + add groups

- src/interfaces/themes/calendar/index.ts
- src/themeDescriptions/themes/calendar/index.ts
> added token

- src/themeDescriptions/themes/vkontakteAndroid/index.ts
fontFamilyAccent для темы vkontakteAndroid был не верным
> fix(vkontakteAndroid): fontFamilyAccent rewrite

- src/build/helpers/convertCamelToSnake.test.ts
- src/build/helpers/convertCamelToSnake.ts
- src/build/helpers/unCamelcasify.test.ts
- src/build/helpers/unCamelcasify.ts
- src/interfaces/general/geometry/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
согласовали их с дизайнерами. (c Алексеем Зайцевым)
Основано на задаче из VKUI: VKCOM/VKUI#6684 и обсуждении https://github.com/VKCOM/VKUI/discussions/5928. C дизайнерами VKUI также обсудили и именно этот набор токенов решено дальше поддерживать.
- добавили новые и изменили существующие токены для системы состояний, например `spacingSizeS`.
- внёс небольшое изменение в преобразование токенов в snake_case, чтобы сохранить группы типа `2Xs` и `3Xs` и `2Xl` вместе, иначе со старой логикой получалось немного странно для таких токенов.
Вот пример для spacingSize2Xl …
> Extend Spacing system

- src/interfaces/general/geometry/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
В первом PR https://github.com/VKCOM/vkui-tokens/pull/830 мы немного немного разошлись с ожиданиями дизайна,  поэтому перетряхиваем значение токенов …
> Change spacing system tokens

- src/interfaces/general/colors/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
Добавил в базовую тему цвет colorIconWarning для предупреждающих иконок
> feat: added colorIconWarning

- src/themeDescriptions/base/vk.ts
Нормализовали подложечные тинт-цвета в тёмной теме и сделали чуть более насыщенный красный тинт в светлой теме.
> fix: tint colors normalization

- src/themeDescriptions/base/vk.ts
Дизайнеры предложили сделать тёмный warning чуть чище, чем он был в жёлтом оттенке. Он стал оранжевым и более насыщенным.
> fix: increased saturation of colorBackgroundWarning

- src/themeDescriptions/base/vk.ts
Починил Icon Secondary Alpha в тёмной теме
> fix: colorIconSecondaryAlpha in dark theme

- src/themeDescriptions/themes/vkCom/index.ts
Изменение нужно, чтобы VKCOM могли безболезненно перевезти шрифты со своих переменных `--palette-vk` на наши токены. 
В предыдущей попытке столкнулись с различием — у нас был `system-ui` в токенах шрифтов, и обновление задело пользователей, которые не пользуются Apple. Теперь `fontFamilyBase` совпадает с `--palette-vk-font`, а `fontFamilyAccent` совпадает с `--vk-sans-display`.
> Updated fonts for vkCom theme

- src/interfaces/general/colors/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
Добавили цвет, который поможет делать акцентные баннеры без явной позитивной / негативной коннотации.
> feat: added colorBackgroundInfoTint

- src/themeDescriptions/themes/vkCom/index.ts
> fix(vkCom): fonts lodash merge

- src/build/helpers/getGradientPointsFromColor.test.ts
- src/build/helpers/getGradientPointsFromColor.ts
Свели карту прозрачности градиентов к более «круглым» числам.
> feat: Rounded values for gradient stops

- src/themeDescriptions/themes/vkCom/index.ts
Починил шрифты, которые по ошибке остались акцентными в теме vkCom.
Это изменение нужно, чтобы vkcom смогли обновиться на `vkui-tokens@latest` и не поломать заголовки.
> fix(vkCom): False accent fonts

- src/themeDescriptions/base/vk.ts
Привёл Background Contrast Themed и Background Contrast Inverse к единому цвету в тёмной версии базовой темы.
> fix(vkBase): Background Contrast Themed = Background Contrast Inverse

- src/build/themeProcessors/customMedia/customMedia.ts
`Object.keys` уже возвращает `array` и в данном случае лишний spread только создает лишнюю промежуточную коллекцию.
> fix: remove needless spread for array

- src/themeDescriptions/themes/vkCom/index.ts
Поправил токен backgroundSecondaryAlpha, который раньше был более голубым и непрозрачным.
Цвет на фоне Background / Content будет ближе к обычному Secondary цвету.
> fix(vkCom): Desaturated and transparent backgroundSecondaryAlpha

- src/themeDescriptions/themes/vkCom/index.ts
Обновил альтернативный акцентный цвет в вккоме. Раньше он совпадал с обычным акцентным, теперь совпадает с акцентным VKUI.
> feat(vkCom): Alternative accent color (bright blue)

- package.json
- src/interfaces/themes/legoAndroid/index.ts
- src/interfaces/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/lego/android.ts
- src/themeDescriptions/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/vkontakteCom/index.ts
Внёс colorStrokePrimary в интерфейс vkontakteAndroid, потому что договорились, что все темы для андроида будут с единым набором токенов.
> fix(vkontakteCom, vkontakteAndroid): Included colorStrokePrimary

- .github/workflows/reusable_workflow_test.yml
- .gitignore
- package.json
Используем обычный json для покрытия, вместо junit
> ci(test): fix coverage file

- src/themeDescriptions/base/vk.ts
Изменены значения цветов для hover- и active-состояний `colorBackgroundSecondaryAlpha`. Были указаны вручную (`rgba(255, 255, 255, 0.12)` и `rgba(255, 255, 255, 0.14)`), теперь дефолтно генерируются (`rgba(255, 255, 255, 0.14)` и `rgba(255, 255, 255, 0.18)`)
Не содержит подъём версии
> fix(vkBase): Updated colorBackgroundSecondaryAlpha states for dark mode

- src/themeDescriptions/base/vk.ts
Обновил дефолтную жирность стиля Title 2 в соответствии с дизайном
> fix(vkBase): Updated Title2 weight accordingly to design
