VKCOM/vkui-tokens

- .github/workflows/publish_from_git.yml
- package.json
Поправил публикацию пакета, чтобы можно было публиковать в паблик из мануального экшена
> Fix publish package

- src/themeDescriptions/base/vk.ts
- src/themeDescriptions/themes/octaviusVK/index.ts
поправил значения цветов для вк почты
> Fix octavius theme vk fix 01

- src/interfaces/themes/media/index.ts
- src/interfaces/themes/pharma/index.ts
- src/themeDescriptions/themes/media/index.ts
- src/themeDescriptions/themes/pharma/index.ts
убрал лишний шаг адаптивности, перевёл на новые шрифты, убрал переопределение шрифта на таче, добавил новые специфичные токены типографики и поправил токены для сетки
> обновил токены медиа и аптек под редизайн

- jest.config.js
- package-lock.json
- package.json
- src/build/compilers/index.ts
- src/build/compilers/styles/compileStyles.ts
- src/build/index.ts
> Починка проблем со сборкой и публикацией

- src/themeDescriptions/themes/octavius/index.ts
* Обновил значение токена `octaviusColorContentScrollbar`
> update-token-value: update content scrollbar token value

- package-lock.json
- package.json
- src/interfaces/themes/media/index.ts
- src/themeDescriptions/common/colors/socialColors.ts
- src/themeDescriptions/common/index.ts
- src/themeDescriptions/themes/media/index.ts
Добавление цветов социальных сетей в тему Media
> feat(media): add socialColors

- package.json
- src/themeDescriptions/themes/media/index.ts
Изменения размеров кнопок и инпутов в теме `media`
> feat(media): change sizes button & field

- src/interfaces/themes/vkBaseDark/index.ts
- src/themeDescriptions/base/vk.ts
- src/themeDescriptions/index.ts
> Заэкспортировать тёмную тему VK

- package-lock.json
- package.json
- src/interfaces/themes/vkAndroid/index.ts
- src/interfaces/themes/vkIOS/index.ts
- src/themeDescriptions/index.ts
- src/themeDescriptions/themes/vkAndroid/index.ts
- src/themeDescriptions/themes/vkIOS/index.ts
> Завести подтемы VK для iOS и Android

- .github/workflows/publish_dev.yml
- .github/workflows/publish_release.yml
> vkui-66: forgot to change dev publish command back to something meaningful

- src/build/compilers/index.ts
- src/build/compilers/styles/compileStyles.test.ts
- src/build/compilers/styles/compileStyles.ts
- src/build/helpers/getAllButColors.test.ts
- src/build/helpers/getAllButColors.ts
Добавил экспорт всех токенов, кроме цветов. Нужно для VKUI.
> added noColors output

- src/themeDescriptions/base/vk.ts
- src/themeDescriptions/themes/vkCom/index.ts
- vkBase.fontTitle3.regular.lineHeight: 24 => 22
- vkBase.sizeButtonSmallHeight.compact: 26 => 28
- vkCom.sizeBorderRadius.regular: 8 => 4
> Fixed token values

- src/interfaces/themes/media/index.ts
- src/themeDescriptions/themes/media/index.ts
Добавил новые шрифтовые токены для статьи. Обновил значения в существующих токенах в соответствии с макетом
> Добавил/обновил шрифтовые токены для media

- src/themeDescriptions/base/vk.ts
> Поменял значение colorFieldBorderAlpha

- src/interfaces/themes/calendar/index.ts
- src/themeDescriptions/themes/calendar/index.ts
Добавил кастомные бордер радиусы для календаря и тень для хедера календаря
> add calendar border radius tokens and header shadow

- src/build/helpers/getGradientPointsFromColor.ts
- src/interfaces/general/gradients/index.ts
- src/interfaces/general/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
Добавил функцию, которая генерирует точки градиента из цвета и множетеля прозрачности; добавил значения градиентов для светлой и темной темы. Осталось разобраться с типизацией
> Генерация точек градиентов с изингами

- src/themeDescriptions/base/vk.ts
- src/themeDescriptions/themes/vkCom/index.ts
- src/themeDescriptions/themes/vkIOS/index.ts
> fix: dark gradients

- .gitignore
- jest.config.js
- package.json
- tasks/styleguide.sh
Добавляет возможность запустить styleguide для просмотра изменений в токенах
> chore: add styleguide

- src/interfaces/themes/search/index.ts
- src/themeDescriptions/themes/search/index.ts
> vkui search theme typography update

- src/interfaces/general/geometry/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
- src/themeDescriptions/themes/vkCom/index.ts
- src/themeDescriptions/themes/vkIOS/index.ts
Токен для задания высоты шапки
> feat(base, vkCom, vkIOS): Add PanelHeader height token

- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/index.ts
- src/themeDescriptions/themes/octavius/index.ts
> Добавил токен themeNameBase в тему paradigmBaseDark

- src/interfaces/themes/octavius/index.ts
- src/themeDescriptions/themes/octavius/index.ts
> Added tokens for cross navigation in octavius theme

- src/themeDescriptions/base/vk.ts
> fix: remove TT Commons

- .github/workflows/coverage.yml
> Обновляю и пытаюсь починить jest-coverage-report-action

- src/themeDescriptions/themes/vkCom/index.ts
Исправляем `colorBackgroundAccentThemed` и `colorTextAccentThemed`
> fix(vkCom): change `colorBackgroundAccentThemed`

- src/interfaces/themes/calendar/index.ts
- src/themeDescriptions/themes/calendar/index.ts
> Calendar buttons colors

- src/themeDescriptions/themes/vkCom/index.ts
> fix(vkCom): поправил цвет `colorIconAccentThemed`

- src/interfaces/themes/octavius/index.ts
- src/themeDescriptions/themes/octavius/index.ts
> fmail-18007: updated tokens for empty state button

- jest.config.js
- package.json
- src/build/compilers/docs/__test__/emptyTheme.ts
- src/build/compilers/docs/__test__/testBaseForBase.ts
- src/build/compilers/docs/__test__/testBaseTheme.ts
- src/build/compilers/docs/__test__/testRecursiveReexport.ts
- src/build/compilers/docs/__test__/testTheme.ts
- src/build/compilers/docs/compileDocsJSON.test.ts
- src/build/compilers/docs/compileDocsJSON.ts
- src/build/compilers/index.ts
- src/build/helpers/cssHelpers.ts
- src/build/index.ts
- src/interfaces/general/animations/index.ts
- src/interfaces/general/colors/index.ts
- src/interfaces/general/elevation/index.ts
- src/interfaces/general/geometry/index.ts
- src/interfaces/general/gradients/index.ts
- src/interfaces/general/index.ts
- src/interfaces/general/toneValues/index.ts
- src/interfaces/general/typography/index.ts
- src/interfaces/namespaces/paradigm/index.ts
- yarn.lock
> Add theme properties docs aggregation

- .github/workflows/publish_release.yml
> ci: Upload Release Asset

- jest.config.js
- src/build/compilers/index.ts
- src/build/compilers/structJSON/compileStructJSON.test.ts
- src/build/compilers/structJSON/compileStructJSON.ts
- src/build/index.ts
> feat: add struct json

- package.json
- yarn.lock
> fix(vkCom): update Appearance to 9.51.4

- src/interfaces/themes/search/index.ts
- src/themeDescriptions/themes/search/index.ts
> vkui search theme typography updated september

- .github/workflows/publish_release.yml
> Чиню загрузку артефактов при сборке

- src/interfaces/themes/octavius/index.ts
- src/themeDescriptions/themes/octavius/index.ts
> colors and snap

- src/interfaces/themes/octavius/index.ts
- src/themeDescriptions/themes/octavius/index.ts
> octaviusColorListBackgroundPositiveTagsOutline token

- src/interfaces/themes/octavius/index.ts
- src/themeDescriptions/themes/octavius/index.ts
> Add octavius color list background positive tags outline

- src/themeDescriptions/base/paradigm.ts
> revert paradigm dark secondary background changes

- src/interfaces/general/animations/index.ts
- src/interfaces/general/colors/index.ts
- src/interfaces/general/typography/index.ts
- src/interfaces/namespaces/paradigm/index.ts
> Перенос документации по токенам в jsdoc

- docs/src/components/pages/Tokens/TokensActions/TokensActions.tsx
- docs/src/components/pages/Tokens/TokensContent/TokensContent.helpers.ts
- docs/src/pages/Tokens.tsx
- docs/src/shared/hooks/useDebounce.ts
- src/interfaces/general/elevation/index.ts
- src/interfaces/general/geometry/index.ts
- src/interfaces/general/gradients/index.ts
- src/interfaces/general/index.ts
- src/interfaces/general/toneValues/index.ts
- src/interfaces/namespaces/paradigm/index.ts
> JSDoc: часть 2

- src/themeDescriptions/themes/octaviusVK/index.ts
…ground tokens for octaviusVKDark theme
> Changed two tokens in octaviusVKDark theme

- src/themeDescriptions/themes/media/index.ts
Исправление значений `letter-spacing` для темы `media`
> fix letter-spacing value in media theme

- src/build/compilers/structJSON/compileStructJSON.ts
- src/build/themeProcessors/pixelifyValues/pixelifyValues.ts
- src/interfaces/general/index.ts
- src/interfaces/general/zIndex/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
Добавляем токены для возможности изменения
положения по оси z всплывающих и модальных окон
- see VKCOM/VKUI#3633
> feat: add z-index

- src/interfaces/themes/calendar/index.ts
- src/lint/__snapshots__/lint.test.ts.snap
- src/themeDescriptions/themes/calendar/index.ts
> feat(calendar): new colors

- src/interfaces/themes/calendar/index.ts
- src/themeDescriptions/themes/calendar/index.ts
> Добавление новых токенов для обновленной белой темы Календаря

- src/themeDescriptions/themes/vkCom/index.ts
Устанавливаем правильный размер модалок для темы vkCom
---
- caused by https://github.com/VKCOM/VKUI/issues/3637
> fix(vkCom): set sizePopupSmall

- src/themeDescriptions/base/vk.ts
> feat(vkBase): rm VK Sans dependencies

- README.md
> docs/pages-link: add doc line

- package.json
- src/interfaces/themes/calendar/index.ts
- src/themeDescriptions/themes/calendar/index.ts
> feat(calendarx): add new tokens for themes

- src/interfaces/themes/calendar/index.ts
- src/themeDescriptions/themes/calendar/index.ts
> fix: oooops, move image background to overvalues from colors

- src/interfaces/namespaces/vk/index.ts
- src/interfaces/themes/vkBase/index.ts
- src/interfaces/themes/vkBaseDark/index.ts
- src/themeDescriptions/base/vk.ts
> feat(vk): add gradients

- src/themeDescriptions/themes/media/index.ts
В теме `media` поменялись значения размера и начертания шрифта для токена `mediaFontMediaLead`
> change article lead typography in media theme

- package.json
- src/interfaces/themes/calendar/index.ts
- src/themeDescriptions/themes/calendar/index.ts
> feat: new token

- src/build/helpers/appearance.test.ts
- src/build/helpers/appearance.ts
- src/interfaces/namespaces/vk/index.ts
- src/lint/__snapshots__/lint.test.ts.snap
- src/themeDescriptions/base/vk.ts
- src/themeDescriptions/themes/vkCom/index.ts
- src/themeDescriptions/themes/vkIOS/index.ts
- tsconfig.publish.json
> feat(vk): add local colors

- src/interfaces/themes/calendar/index.ts
- src/themeDescriptions/themes/calendar/index.ts
> feat: new themes tokens

- src/themeDescriptions/base/paradigm.ts
> Поправил токен BackgroundTertiary

- src/interfaces/general/geometry/index.ts
- src/interfaces/general/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
> feat(base): Add base spacing tokens

- src/interfaces/general/typography/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
> feat(typography): add fontFamilyFallbacks

- src/interfaces/themes/calendar/index.ts
- src/themeDescriptions/themes/calendar/index.ts
> CLND-9167: new calendar tokens

- .github/CODEOWNERS
> process/codeowners: add designers to codeowners

- CONTRIBUTING.md
- src/interfaces/themes/workspaceAdmin/index.ts
- src/themeDescriptions/index.ts
- src/themeDescriptions/themes/workspaceAdmin/index.ts
> feat: new theme workspaceAdmin

- README.md
- docs/articles/new-theme/INDEX.md
> docs/new-theme: add new theme guide

- docs/src/pages/Tokens.tsx
> docs/themes-sorting: fix themes sorting

- src/interfaces/general/geometry/index.ts
- src/interfaces/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
- src/themeDescriptions/themes/vkCom/index.ts
- src/themeDescriptions/themes/vkontakteCom/index.ts
Добавили большой вариант скругления для карточек 16px = vkBase и 20px = Paradigm
> Add M size token for BorderRadius

- .github/workflows/coverage.yml
> fix/coverage: change coverage report action version

- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
Используем размер по ширине iPhone 14 Pro Max
> fix(sizePopupSmall): use iPhone 14 Pro Max size

- src/themeDescriptions/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/vkontakteCom/index.ts
- src/themeDescriptions/themes/vkontakteIOS/index.ts
Исправляем themeNameBase для тем vkontakte*
> fix(vkontakte): themeNameBase

- src/themeDescriptions/base/paradigm.ts
> change shadow in paradigm

- src/build/themeProcessors/pixelifyValues/pixelifyValues.test.ts
- src/build/themeProcessors/pixelifyValues/pixelifyValues.ts
- src/interfaces/general/geometry/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
- src/themeDescriptions/themes/vkCom/index.ts
> feat: add sizeBorder

- .github/workflows/coverage.yml
- package.json
> fix problems

- .github/workflows/coverage.yml
> fix/coverage-perms: add coverage permissions

- package.json
- src/interfaces/general/tools/utils.ts
- src/themeDescriptions/base/vk.ts
- src/themeDescriptions/themes/vkontakteAndroid/index.ts
- yarn.lock
Добавляем letterSpacing для vkontakteAndroid
> feat(vkontakteAndroid): add letterSpacing

- src/themeDescriptions/themes/calendar/index.ts
> fix: update calendar fonts tokens

- src/themeDescriptions/themes/vkontakteAndroid/index.ts
Добавляем акцентный шрифт VK Sans Display
> feat(vkontakte*): add VK Sans Display

- src/themeDescriptions/base/figma/vk.json
- src/themeDescriptions/base/vk.ts
Исправляем accent_raspberry_pink
> fix: update colorAccentRaspberryPink

- src/themeDescriptions/themes/vkCom/index.ts
> fix(vkCom): remove 1px border

- src/interfaces/general/typography/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
- src/themeDescriptions/themes/vkCom/index.ts
- src/themeDescriptions/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/vkontakteCom/index.ts
- src/themeDescriptions/themes/vkontakteIOS/index.ts
Добавляем fontDisplayTitle шрифты
> feat: add fontDisplayTitle

- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
> fix(Gradient): fix Gradient color

- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
- src/themeDescriptions/themes/vkCom/index.ts
- src/themeDescriptions/themes/vkIOS/index.ts
> feat(base): Add PanelHeader compact height token

- src/interfaces/themes/calendar/index.ts
- src/themeDescriptions/themes/calendar/index.ts
> added token

- src/interfaces/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/vkontakteCom/index.ts
> feat(vkontakte): add more tokens

- package.json
В том числе, чтобы отображался в правом меню GitHub.
> chore: add link to doc in package.json

- src/themeDescriptions/themes/calendar/index.ts
> CLND-9864: refactor tokens

- src/interfaces/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/vkontakteCom/index.ts
Добавляем цвета для vkontakte
- `vkontakteLandingSecondaryButtonBackground`
- `vkontakteStoriesSkeletonLoaderBackground`
> feat(vkontakte): add 2 colors

- src/themeDescriptions/themes/vkCom/index.ts
Заменены цвета:
Dark
colorBackgroundPositiveTint: `#b1d6b1` -> `#2F422F`,
> fix(vkCom): Positive & Negative Tint

- src/interfaces/themes/dobro/index.ts
- src/themeDescriptions/themes/dobro/index.ts
> VK Dobro updates custom-media

- src/interfaces/themes/media/index.ts
- src/themeDescriptions/themes/media/index.ts
> update media theme with new typography

- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
Уменьшил межстрочный интервал для fontDisplayTitle4: 24 → 22
> fix: smaller line height for fontDisplayTitle4

- src/interfaces/themes/octavius/index.ts
- src/themeDescriptions/themes/octavius/index.ts
> add snackbar tokens

- src/interfaces/themes/vkIdOk/index.ts
- src/interfaces/themes/vkIdOkDark/index.ts
- src/interfaces/themes/vkIdOkIOS/index.ts
- src/interfaces/themes/vkIdOkIOSDark/index.ts
- src/themeDescriptions/index.ts
- src/themeDescriptions/themes/vkIdOk/index.ts
- src/themeDescriptions/themes/vkIdOkIOS/index.ts
> Added vkidok theme

- src/themeDescriptions/themes/vkIdOk/index.ts
> Update colors for vkidok theme

- src/interfaces/themes/cloud/index.ts
- src/themeDescriptions/themes/cloud/index.ts
> Cloud theme updating

- .editorconfig
- README.md
---
- поправлено форматирование в `Readme.md`, чтобы примеры с кодом выглядели ровнее
- доработан пример с локальной сборкой тем
> feat: Rewrite docs for personal themes & fix readme formatting

- src/themeDescriptions/base/vk.ts
Затемняем цвет модалки, чтобы пофиксить контрастность элементов, которые могут на неё отображаться и приблизить её цвет к colorBackgroundContent.
> feat: Darkened colorBackgroundModal in dark theme

- src/interfaces/themes/vkAccessibility/index.ts
- src/interfaces/themes/vkAccessibilityDark/index.ts
- src/interfaces/themes/vkAccessibilityIOS/index.ts
- src/interfaces/themes/vkAccessibilityIOSDark/index.ts
- src/themeDescriptions/index.ts
- src/themeDescriptions/themes/vkAccessibility/index.ts
- src/themeDescriptions/themes/vkAccessibilityIOS/index.ts
- src/themeDescriptions/themes/vkIOS/index.ts
Добавили тему с повышенной контрастностью для вторичных и третичных цветов
> feat: Added accessibility theme

- src/themeDescriptions/themes/calendar/index.ts
> CLND-10355: calendar font family

- .yarnrc.yml
- src/themeDescriptions/base/vk.ts
Поправил ошибочно проставленные акцентные шрифты
> fix(vkBase): Linked non-display font tokens to fontFamilyBase

- src/interfaces/themes/workspaceAdmin/index.ts
- src/interfaces/themes/workspaceAdminDark/index.ts
- src/themeDescriptions/index.ts
- src/themeDescriptions/themes/workspaceAdmin/index.ts
Обновление тем WorkspaceAdmin и WorkspaceAdminDark
> feat: updating workspaceAdmin theme

- src/themeDescriptions/themes/workspaceAdmin/index.ts
- работает сборка (`npm run build:local`),
- проходят тесты (`npm test`),
- проходит линтер (`npm run lint`)
Задача: https://jira.vk.team/browse/BIZ-14650
**Мержить только после https://github.com/VKCOM/vkui-tokens/pull/944**
> Workspace admin colors change

- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/themes/calendar/index.ts
- src/themeDescriptions/themes/octavius/index.ts
> feat: Paradigm change fonts

- src/interfaces/themes/media/index.ts
- src/themeDescriptions/themes/media/index.ts
Добавлен токен для типографики.
Добавлены токены для сетки
> media theme: new tokens are added

- src/interfaces/namespaces/paradigm/index.ts
- src/themeDescriptions/base/paradigm.ts
> Синхронизация с библиотекой Figma, обновление темы Paradigm

- src/themeDescriptions/common/colors/projectColors.ts
- src/themeDescriptions/themes/media/index.ts
> feat: new font and color project

- src/themeDescriptions/themes/workspaceAdmin/index.ts
- работает сборка (`npm run build:local`),
- проходят тесты (`npm test`),
- проходит линтер (`npm run lint`)
Задачи: 
https://jira.vk.team/browse/BIZ-13587
https://jira.vk.team/browse/BIZ-14960
> feat: change vkws tokens

- src/interfaces/themes/cloud/index.ts
- src/themeDescriptions/themes/cloud/index.ts
> feat: refactor cloud theme

- src/themeDescriptions/common/colors/projectColors.ts
> Color rebranding realty

- src/themeDescriptions/themes/octavius/index.ts
> NOTASK: fix

- src/themeDescriptions/base/paradigm.ts
> Поправил значения Negative цветов

- src/themeDescriptions/themes/media/index.ts
> media: update tokens

- src/interfaces/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/vkCom/index.ts
- src/themeDescriptions/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/vkontakteCom/index.ts
Resolves #1082 
Добавил чернюще-черный цвет в тему vkCom.
> feat(vkontakteCom): Added colorAccentBlack

- package.json
- src/interfaces/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/vkCom/index.ts
- src/themeDescriptions/themes/vkontakteAndroid/index.ts
- src/themeDescriptions/themes/vkontakteCom/index.ts
**Новые токены**
- В тему `vkontakteCom` добавлен токен `colorPaletteBlack` #1088 @qurle
**Изменённые токены**
- В теме `vkCom` изменено значение `colorBackgroundAccentAlternative` #1121 @qurle
> feat: 4.56.0 version

- package.json
4.56.1 version
**Изменённые токены**
- В теме `workspaceAdmin ` изменены значения шрифтов #1106 @kre0n
> feat: 4.56.1 version

- package.json
**Инфраструктура**
- Исправлена хелпер-функция `gradient()` — теперь для CSS-вывода она привязывает не все точки градиента к указанной переменной, а только основную (#1131 by @qurle)
> feat: 4.56.2 version

- package.json
**Новые токены**
- Добавлена новая тема (#1110)
> feat: 4.57.0

- package.json
- src/themeDescriptions/themes/vkIdOk/index.ts
Обновился цвет colorTextAccentThemed в тёмной теме vkIdOk c оранжевого на белый.
> fix(vkIdOk): Updated dark theme color for colorTextAccentThemed

- package.json
- src/themeDescriptions/base/vk.ts
Обновлена жирность по умолчанию в шрифте fontFootnoteCaps: Regular → Semibold
Теперь жирность совпадает со значением в макетах, и согласуется с другими капсовыми шрифтами.
> fix(vkBase): fontFootnoteCaps is now semibold

- src/themeDescriptions/base/paradigm.ts
> Поправил дефолтный шрифт на системный

- package.json
> fix: 4.61.3 version

- src/interfaces/themes/calendar/index.ts
- src/lint/__snapshots__/lint.test.ts.snap
- src/themeDescriptions/themes/calendar/index.ts
> Добавил новый цвет calendarColorSidebarItemBackground в тему календаря

- package.json
> feat: 4.62.0

- src/interfaces/themes/media/index.ts
- src/themeDescriptions/themes/media/index.ts
> feat: add mediaFontMediaFeatureTitle for Feature component

- package.json
> feat: 4.63.0

- package.json
- src/build/compilers/structJSON/compileStructJSON.ts
- src/interfaces/general/effects/index.ts
- src/interfaces/general/index.ts
- src/themeDescriptions/base/paradigm.ts
- src/themeDescriptions/base/vk.ts
Добавлен токен `blurM` во все темы. В struct.json теперь генерируется группа `blur`
**Содержит подъём версии**
> feat: Blur-токены

- package.json
> feat: 4.66.0

- package.json
> feat: up version to 4.67.0

- package.json
> feat: Minor version update
